### ISSUE TITLE
Summation on booleans returns OR instead of sum

### ISSUE THREAD

**Issue by aulemahal** [dcherian/flox#100]
As explained in pydata/xarray#6615, it seems the `sum` aggregations implemented by flox actually return an OR reduction when given boolean inputs. While this could be seen as mathematically/technically correct, it is a different behaviour than `numpy`.

However, testing with `flox` directly, I see that the `numpy` engine actually raises an error with boolean types. I'm guessing the `flox` one should too? But then, I'm not sure how xarray should handle it... A special case for `sum` here (`xarray_reduce`) or there?

Culprit line:
https://github.com/dcherian/flox/blob/19543801fb28f2557591aecd559e52b66c8051b3/flox/aggregate_flox.py#L51

MWE:
```python3
import flox
import numpy as np

groups = np.array([1, 1, 1])
data = np.array([True, True, False])

np.sum(data) # 2, what I expect

flox.groupby_reduce(data, groups, func='sum', engine='flox')  # (True, 1) , the result of an OR agg.

flox.groupby_reduce(data, groups, func='sum', engine='numpy')   # Fails within numpy_groupies, same with numba
#  TypeError: function sum requires a more complex datatype than bool
```

**Comment by dcherian** [comment]
Since `np.sum` works we can cast `bool` to `int` in https://github.com/dcherian/flox/blob/19543801fb28f2557591aecd559e52b66c8051b3/flox/core.py#L1343
when `func not in ["all", "any"]`
